name: Dockerize
on:
  push:
    branches:
      - feature/dockerize
jobs:
  build:
    name: 🏗️ Install and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: docker login
        env:
          DOCKER_USER: 'rachitgod'
          DOCKER_PASSWORD: 'd003c125-a1f0-4bd8-a383-44d9d5cd07b1'

        run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 


      - name: build image
        run: docker build . --file Dockerfile -t tatum-kms:latest 
    
      - name: push image
        run: docker push $DOCKER_USER/tatum-kms:latest 